### ISSUE TITLE
ERROR ILSpy.app” is damaged and can’t be opened. You should move it to the Trash

### ISSUE THREAD

**Issue by Darkcast** [icsharpcode/AvaloniaILSpy#144]
version ILSpy 7.2 RC
MacOS 14.0 M1
also tried 7.1 RC

![image](https://github.com/icsharpcode/AvaloniaILSpy/assets/1676655/15f89f8f-5e6e-4a1e-8391-f11b1fed9dfb)

**Comment by Hecatoplex** [comment]
Try `sudo xattr -d com.apple.quarantine path/to/ILSpy.app` in the terminal, then reopening it.

**Comment by danielkraut** [comment]
I has the same problem and fix by @Hecatoplex did work. Thanks.

**Comment by Darkcast** [comment]
> Try `sudo xattr -d com.apple.quarantine path/to/ILSpy.app` in the terminal, then reopening it.

this worked, thanks man :)

**Comment by Darkcast** [comment]
issue fixed

**Comment by bitbonk** [comment]
I just installed ILSpy via homebrew using `brew install --cask ilspy` and then ran `sudo xattr -d com.apple.quarantine /Applications/ILSpy.app`. It did not help, the same error comes up.

**Comment by mapitman** [comment]
When installing via Homebrew, this worked for me:
```
brew install --cask --no-quarantine ilspy

**Comment by smileBeda** [comment]
This is not a fix, this is a hack. The fix is to use proper signatures, and installing any thing that is not properly signed shouldn't be done.
This tool should be considered abandoned if the maintainers are not adjusting the application, not hacked around to make it work anyway by bypassing apples' security features.

By removing the com.apple.quarantine attribute, you are effectively telling macOS that the file is safe to open and run without undergoing Gatekeeper’s security checks. This can be useful if you **trust the application** and want to bypass the warning dialogs that macOS presents when opening a quarantined file for the first time.
Do you trust anything on the web? I do not.
